name: Deploy Node to VPS (self-hosted)
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash -leo pipefail {0}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            **/package-lock.json
      - name: Build (nếu có)
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi
          if npm run | grep -q "build"; then npm run build; fi
      - name: Rsync sang thư mục chạy thật
        run: |
          rsync -az --delete --exclude=".git" --exclude="node_modules" --exclude=".env*" ./ /var/www/myapp/
      - name: Chown cho deploy sau khi rsync
        run: |
          chown -R deploy:deploy /var/www/myapp

      - name: Cài deps production & restart PM2 (chạy dưới user deploy)
        run: |
          sudo -u deploy bash -lc '
            . ~/.nvm/nvm.sh
            cd /var/www/myapp
            if [ -f package-lock.json ]; then npm ci --omit=dev; else npm i --omit=dev; fi
            pm2 startOrReload ecosystem.config.cjs || pm2 start ecosystem.config.cjs
            pm2 save
          '
